### ISSUE TITLE
Problem in saving a trained model !

### ISSUE THREAD

**Issue by sstajinder1** [mon95/Sign-Language-and-Static-gesture-recognition-using-sklearn#2]
Hello Sir, @mon95. Your work is amazing !! I'm new to working on python and have usually used MATLAB. I'm unable to understand the .pkl files part. How to train, store and retrieve it back as your instructions were:

>Using gesture_recognizer1.py:
>    Modify the main function in gesture_recognizer1.py to use the correct list of users. Train and save the gesture recognizer. (Uncomment the lines in main() accordingly) https://github.com/mon95/Sign-Language-and-Static-gesture-recognition-using-sklearn/blob/master/dataset/gesture_recognizer1.py#L509
>    Then, use the load_model method to load the previously saved gesture recognizer objec. Now, the test images, can be tested using the recognize_gesture function.

I changed line 509 to 
> userlist=['user_5','user_9','user_10']
And changed file path correctly in line 508.

Everything in def main() is commented in the .py file, so I'm finding it hard to decide which ones to uncomment for training and , creating and using these" handDetector.pkl, signDetector.pkl, model_log_2.pkl " and they weren't in .../dataset/
Kindly help me understand how to do this, " Train and save the gesture recognizer." step by step as I'm new to this.

Thank You 😃

**Comment by mon95** [comment]
Hi! 

Thank you :) 

Yes, all the .pkl files are files that we generated and continued to use. You do not need any of these. 

Write a line invoking the constructor that takes in only the directory-path as the input i.e., something like:
`gs = GestureRecognizer('/home/your/path/dataset/')  ` (change the path accordingly)

Then, use lines 509-514 to train your model.

For most use-cases, you'll probably want to customise the main function to your needs:

Refer to my [blog explaining the code](https://medium.freecodecamp.com/weekend-projects-sign-language-and-static-gesture-recognition-using-scikit-learn-60813d600e79) so that you can work with the rest of the code. 

Hope this helps!

Sreehari
